### ISSUE TITLE
Feature Request: Stop Detoriation

### ISSUE THREAD

**Issue by cyrrelsneer** [AlexBoost/Wekod-Soulmask-Docker-Server#1]
Hi,
not sure if that is the correct place to ask this?
But is there a way to stop progress on the server during times when noone is active?
We play mostly with 2 guys and max once a week, but it seems that the dangers during the offline periods are rather high that you lose a lot of the structure?
Would shutting down the server be sufficient or is a ENV somehow possible to stop detoriation during offline periods?

And: Thanks a lot for your work! Works like a charm and a well written how to!

**Comment by AlexBoost** [comment]
Hello, 

Thanks, I hope it saved you a lot of time :)
Unfortunately, there is no way on my side to do that, except, of course, to shutdown the server

From the game server, check that this parameter is well set by using `gm key <YourAdminPassword>` going into `coefficients` then on `General` tab and go down to find this parameter.

![image](https://github.com/AlexBoost/Wekod-Soulmask-Docker-Server/assets/7255921/259d1140-f24a-4550-922a-c9762bb947d7)

Be sure to have clanmate who will farm woods in quantity (craft like 50+ axes and put them in one large chest, they will take it automatically), and most importantly, one assigns on your bonfire ! 
This one will take care of all fires and repair all structures which took damages.

I got a server since 2 or 3 weeks now, I have a huge house, I never repaired anything nor being busying with the bonfire. Everything is automated using clanmate.

**Comment by cyrrelsneer** [comment]
Hey mater, thanks for your reply! Haven't checked the settings yet, have tried to see how it works in default.
And it seems ok right now, if you have the correct working routinges I think they will be good for a while ;-)

Great game, greate effort also by you! thanks again
